name: tests

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    linux:
        runs-on: ubuntu-24.04
        name: Ubuntu 24.04

        steps:
            -   name: Install Swift
                uses: tayloraswift/swift-install-action@master
                with:
                    swift-prefix: "swift-6.0.3-release/ubuntu2404/swift-6.0.3-RELEASE"
                    swift-id: "swift-6.0.3-RELEASE-ubuntu24.04"

            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Run tests
                run: Scripts/TestAll

    macos:
        runs-on: macos-15
        name: macOS

        steps:
            -   name: Install Swift
                uses: tayloraswift/swift-install-action@master
                with:
                    swift-prefix: "swift-6.0.3-release/xcode/swift-6.0.3-RELEASE"
                    swift-id: "swift-6.0.3-RELEASE"

            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Run tests
                run: Scripts/TestAll
